# Generated by Django 2.1 on 2018-08-19 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0002_crop_type_description'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_email', models.CharField(max_length=255)),
                ('seller_contact', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('nearest_town', models.CharField(max_length=255)),
                ('farm_size', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('units', models.CharField(max_length=255)),
                ('unit_price', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/store')),
                ('description', models.TextField(blank=True, null=True)),
                ('crop_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.Crop_Type')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.Region')),
            ],
        ),
    ]
