# Generated by Django 2.1 on 2018-08-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_crop_type_description'),
        ('regions', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store_Items',
            new_name='Store_Item',
        ),
    ]
