# Generated by Django 2.1 on 2018-08-19 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('crops', '0002_crop_type_description'),
        ('store', '0003_auto_20180819_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_email', models.CharField(max_length=255)),
                ('buyer_contact', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('units', models.CharField(max_length=255)),
                ('unit_price', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Store_Item',
            new_name='Store_Product',
        ),
        migrations.AddField(
            model_name='order',
            name='store_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Store_Product'),
        ),
    ]
