# Generated by Django 2.1.2 on 2018-12-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_store_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_product',
            name='units',
            field=models.CharField(choices=[('kg', 'Kg'), ('boxes', 'Boxes'), ('tray', 'Tray'), ('net', 'Net'), ('bunch', 'Bunch')], default='Kg', max_length=255),
        ),
    ]
