# Generated by Django 2.1 on 2018-08-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop_type',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
