# Generated by Django 2.1 on 2018-08-19 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20180819_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire_Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('farm_size', models.CharField(max_length=255)),
                ('farm_location', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('price_per', models.CharField(max_length=255)),
                ('nature_of_work', models.TextField(blank=True, null=True)),
                ('let_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Let_Equipment')),
            ],
        ),
    ]
