# Generated by Django 2.1 on 2018-08-19 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regions', '0001_initial'),
        ('equipment', '0003_hire_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell_Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=255)),
                ('manufacture_year', models.DateField()),
                ('current_location', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/sell/equipment')),
                ('price_range_from', models.CharField(max_length=255)),
                ('price_range_to', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_email', models.CharField(max_length=255)),
                ('owner_contact', models.CharField(max_length=255)),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Equipment_Type')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.Region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='let_equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/let/equipment'),
        ),
    ]
