# Generated by Django 2.1 on 2018-08-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20180819_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_equipment',
            name='price_range_from',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sell_equipment',
            name='price_range_to',
            field=models.IntegerField(),
        ),
    ]
