# Generated by Django 2.1 on 2018-08-19 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_auto_20180819_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('price_to_buy', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('sell_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Sell_Equipment')),
            ],
        ),
        migrations.AddField(
            model_name='hire_equipment',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
