# Generated by Django 2.1.2 on 2018-12-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_auto_20180819_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_equipment',
            name='status',
            field=models.CharField(choices=[('approved', 'APPROVED'), ('pending', 'PENDING')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='hire_equipment',
            name='status',
            field=models.CharField(choices=[('approved', 'APPROVED'), ('pending', 'PENDING')], default='pending', max_length=255),
        ),
    ]
