# Generated by Django 2.1.2 on 2019-01-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_auto_20190112_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire_equipment',
            name='price_per',
            field=models.CharField(choices=[('hr', 'HR'), ('acre', 'ACRE')], default='hr', max_length=255),
        ),
    ]
