# Generated by Django 2.1.2 on 2019-01-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_auto_20190112_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire_equipment',
            name='price_per',
            field=models.CharField(choices=[('hr', 'hr'), ('acre', 'hr')], default='hr', max_length=255),
        ),
        migrations.AlterField(
            model_name='let_equipment',
            name='price_per',
            field=models.CharField(choices=[('hr', 'hr'), ('acre', 'hr')], default='hr', max_length=255),
        ),
    ]
