# Generated by Django 2.1.7 on 2019-07-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_graph_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph_data',
            old_name='crop_type',
            new_name='market',
        ),
        migrations.RemoveField(
            model_name='market',
            name='date_price',
        ),
    ]
