# Generated by Django 2.1.2 on 2018-12-08 16:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request_To_Buy_Offers',
            new_name='Request_To_Buy_Offer',
        ),
        migrations.RenameModel(
            old_name='Request_To_Lease_Offers',
            new_name='Request_To_Lease_Offer',
        ),
    ]
