# Generated by Django 2.1 on 2018-10-29 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regions', '0001_initial'),
        ('agrovets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor_name', models.CharField(max_length=255)),
                ('requestor_email', models.CharField(max_length=255)),
                ('requestor_contact', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_purpose', models.TextField()),
                ('farm_name', models.CharField(max_length=255)),
                ('delivery_location', models.CharField(max_length=255)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.Region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
