# Generated by Django 2.1.2 on 2018-12-26 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agrovets', '0003_auto_20181226_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request_product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
