# Generated by Django 2.1.2 on 2018-12-23 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_farm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_farm',
            name='current_problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register_farm',
            name='farm_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register_farm',
            name='owner_contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_farm',
            name='owner_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_farm',
            name='owner_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_farm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
