# Generated by Django 2.1.2 on 2018-12-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_auto_20181223_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_farm',
            old_name='name',
            new_name='farm_name',
        ),
        migrations.RenameField(
            model_name='register_farm',
            old_name='size',
            new_name='farm_size',
        ),
    ]
