# Generated by Django 2.1 on 2018-08-31 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0002_crop_type_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Agronomist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agronomist_name', models.CharField(max_length=255)),
                ('agronomist_email', models.CharField(max_length=255)),
                ('agronomist_contact', models.CharField(max_length=255)),
                ('profile', models.TextField()),
                ('advice', models.TextField()),
                ('crop_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.Crop_Type')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.Region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Register_Agronomist_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor_name', models.CharField(max_length=255)),
                ('requestor_email', models.CharField(max_length=255)),
                ('requestor_contact', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('nature_of_problem', models.TextField()),
                ('status', models.CharField(default='pending', max_length=255)),
                ('register_agronomist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agronomist.Register_Agronomist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request_Agronomist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('nature_of_problem', models.TextField()),
                ('requestor_name', models.CharField(max_length=255)),
                ('requestor_email', models.CharField(max_length=255)),
                ('requestor_contact', models.CharField(max_length=255)),
                ('crop_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.Crop_Type')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.Region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request_Agronomist_Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offeror_name', models.CharField(max_length=255)),
                ('offeror_email', models.CharField(max_length=255)),
                ('offeror_contact', models.CharField(max_length=255)),
                ('advice', models.TextField()),
                ('status', models.CharField(default='pending', max_length=255)),
                ('request_agronomist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agronomist.Request_Agronomist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
