# Generated by Django 2.1 on 2018-08-31 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crops', '0002_crop_type_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer_Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number_plate', models.CharField(max_length=255)),
                ('vehicle_make', models.CharField(max_length=255)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='images/let/equipment')),
                ('charges_per_km', models.IntegerField()),
                ('offeror_name', models.CharField(max_length=255)),
                ('offeror_email', models.CharField(max_length=255)),
                ('offeror_contact', models.CharField(max_length=255)),
                ('preferred_cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.Crop_Type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer_Transport_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_tones', models.IntegerField()),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('requestor_name', models.CharField(max_length=255)),
                ('requestor_email', models.CharField(max_length=255)),
                ('requestor_contact', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('cargo_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.Crop_Type')),
                ('offer_transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.Offer_Transport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request_Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_tones', models.IntegerField()),
                ('means_of_transport', models.CharField(max_length=255)),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('charges_per_km', models.IntegerField()),
                ('requestor_name', models.CharField(max_length=255)),
                ('requestor_email', models.CharField(max_length=255)),
                ('requestor_contact', models.CharField(max_length=255)),
                ('cargo_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.Crop_Type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request_Transport_Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number_plate', models.CharField(max_length=255)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='images/let/equipment')),
                ('charges_per_km', models.IntegerField()),
                ('offeror_name', models.CharField(max_length=255)),
                ('offeror_email', models.CharField(max_length=255)),
                ('offeror_contact', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('request_transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.Request_Transport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
